return {
  { -- restrict updating lazy.nvim to released versions
    "folke/lazy.nvim",
    version = "*",
  },
  { import = "plugins.editor.which-key" },
  { import = "plugins.editor.snacks" },
  { import = "plugins.editor.fidget" },
  { import = "plugins.editor.neo-tree" },
  { import = "plugins.editor.todo-comments" },
  { import = "plugins.editor.flash" },
  { import = "plugins.editor.undotree" },
  { import = "plugins.editor.gitsigns" },
  { import = "plugins.editor.bufferline" },
  { import = "plugins.editor.lualine" },
  { import = "plugins.editor.treesitter" },
  { import = "plugins.editor.completion" },
  { import = "plugins.editor.b64" },
  { import = "plugins.editor.persistence" },
  { import = "plugins.editor.catppuccin" },
  { import = "plugins.editor.nvim_tmux_navigation" },
  { import = "plugins.editor.smear_cursor", enabled = vim.g.nvc.editor.smear_cursor.enabled },
}
